# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:20.04"
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:20.04"
  armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:20.04"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Modem Syncer"
  org.opencontainers.image.description: "Addon for control the vodafone station 6"
  org.opencontainers.image.source: "https://github.com/dydoc/addon-modem-syncer.git"
  org.opencontainers.image.licenses: "GPL-3.0"
args:
  TEMPIO_VERSION: "2021.09.0"
